d-apache:
  ports:
  - 65503:22/tcp
  - 65504:80/tcp
  environment:
    DWL_SSH_ACCESS: 'true'
    DWL_USER_NAME: username
    DWL_USER_PASSWD: secret
    DWL_USER_ID: '1000'
  labels:
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: apache.davaskweblimited.com
  image: davask/d-apache:2.4-u14.04
  volumes:
  - /path/to/files:/home/username/files
  - /path/to/sites-available:/etc/apache2/sites-available
  stdin_open: true
